Better failure handling

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -34,5 +34,9 @@ do
   full_cmd="cd $build_dir && $cmd"
   echo "DEPLOY_TASK_$i) Running: $full_cmd"
   eval $full_cmd
-done
 
+  if [ $? -ne 0 ]; then
+    echo "DEPLOY_TASK_$i failed to run properly, exit value was: $?"
+    exit $?
+  fi
+done
